py.install_sources(
     'agent.py',
     'class_kea.py',
     'dhcp4_global.py',
     'dhcp4_hooks.py',
     'dhcp4_loggers.py',
     'dhcp4_nets.py',
     'dhcp4_peers.py',
     'dhcp4.py',
     'dhcp4_reserved.py',
     'dhcp4_top.py',
     '__init__.py',
     'tools.py',
     'version.py',
     'write_configs.py',
  subdir: 'kea_config_mod/kea'
)
