#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2022-present Gene C <arch@sapience.com>
# 
# installer script for kea_config
#  e.g. Call from PKGBUILD:  
#   ./do-install ${pkgdir}
# gene c (2022)
#
#dest=${dest%/}
dest="$1"
self="kea_config"
mod="kea_config_mod"

info="README.rst Docs configs packaging"
infodir="/usr/share/${self}"

license_src="Docs/License/License.rst"
licensedir="/usr/share/licenses/${self}"

# list apps without the ".py" or leave empty string
# 
apps=("kea-config")

# so can make app link in /usr/bin
sitedir=$(python -c "import site; print(site.getsitepackages()[0])")
installdir="${dest}${sitedir}"
app_location="${sitedir}/${mod}/apps"

uv_opts=(
    --python /usr/bin/python
    --system
    --no-build-isolation
    --link-mode=copy
    --compile-bytecode
)

if [ ! -d "$dest" ] ; then
    echo 'Missing destination directory'
    exit 1
else
    # shared
    /usr/bin/rsync --mkpath -a ${info} ${dest}${infodir}/
    /usr/bin/rsync --mkpath -a ${license_src} ${dest}/${licensedir}/
    
    /usr/bin/uv pip install ${uv_opts[@]} --target "$installdir" dist/*.whl
    /usr/bin/rm -rf "$installdir"/.lock

    # link(s) in /usr/bin/
    if [ -v apps ] ; then
        /usr/bin/mkdir -p "${dest}/usr/bin"
        for app in ${apps[@]}
        do
            /usr/bin/ln -sf ${app_location}/${app}.py ${dest}/usr/bin/${app}
        done
    fi
    exit 0
fi
